Add table validation step to CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,3 +36,12 @@ jobs:
             cat errors.csv
             exit 1
           fi
+      - name: Validate html including tables
+        run: |
+          validate-mbz-html html errors.csv html --tables
+          CSV_LINES=$(wc -l < errors.csv )
+          if [[ $CSV_LINES != "1" ]]; then
+            echo "Validation errors found in html:"
+            cat errors.csv
+            exit 1
+          fi
